project:
  type: website
  output-dir: docs    

website:
  title: "Learning Learning"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Posts
        href: blog.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme:
      - superhero
      - brand
    toc: true

