project:
  type: website
  output-dir: docs


website:
  title: "Learning Learning"
  site-url: https://aaronjames95.github.io/quarto_blog/    
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme:
      - superhero
      - brand
    toc: true

